// Run: npx tsx scripts/seed-real.ts
import { createClient } from "@supabase/supabase-js";
import { config } from "dotenv";
import { resolve } from "path";

config({ path: resolve(__dirname, "../.env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const events = [
  {
    title: "Beyond Bookkeeping: Finance & Strategy for Small Business Owners",
    description: "Learn how clean financials and strategic finance help small business owners make better decisions year-round. Covers financial management and strategic planning for entrepreneurs.",
    start_date: "2026-02-17T18:00:00.000Z",
    end_date: "2026-02-17T19:30:00.000Z",
    location_name: "Startup Junkie",
    location_address: "Fayetteville, AR",
    is_online: false,
    categories: ["startup", "education"],
    source_url: "https://www.eventbrite.com/d/ar--fayetteville/startup/",
    source_platform: "eventbrite",
    organizer_name: "Startup Junkie",
    organizer_company: "Startup Junkie",
    status: "approved",
  },
  {
    title: "Dinner with Entrepreneurs: Small Town, Small Business Edition | Rogers",
    description: "Curated small group dinners (4-6 people) at locally-owned restaurants. Designed to combat loneliness while supporting local businesses. Participants complete a questionnaire about age, hobbies, and interests for compatible matching.",
    start_date: "2026-02-18T01:00:00.000Z",
    end_date: "2026-02-18T03:00:00.000Z",
    location_name: "Restaurant of the Week",
    location_address: "North 2nd Street, Rogers, AR 72756",
    is_online: false,
    categories: ["networking", "community"],
    source_url: "https://www.eventbrite.com/e/dinner-with-entrepreneurs-small-town-small-business-edition-rogers-tickets-1977166835228",
    source_platform: "eventbrite",
    organizer_name: "Ermantourage Sports",
    status: "approved",
  },
  {
    title: "February Happy Hour at the Leroy Lounge",
    description: "A relaxed, free networking happy hour celebrating Black entrepreneurs and creatives, open and welcoming to everyone. Connect with small business owners, entrepreneurs, and innovators over drinks. Free drinks while supplies last (21+).",
    start_date: "2026-02-19T23:30:00.000Z",
    end_date: "2026-02-20T01:30:00.000Z",
    location_name: "The LeRoy Lounge",
    location_address: "Metro District Lofts area, Fayetteville, AR",
    is_online: false,
    categories: ["networking", "community"],
    source_url: "https://kiva-nwa.org/event/february-happy-hour-at-the-leroy-lounge/",
    source_platform: "eventbrite",
    organizer_name: "Kiva Northwest Arkansas Hub",
    organizer_company: "Kiva NWA",
    status: "approved",
  },
  {
    title: "AI in Action for Retail — Half-Day Workshop",
    description: "Half-day workshop on AI for Retail Analysis, Reporting & Decision-Making. Hands-on exploration of AI tools applied to the retail industry.",
    start_date: "2026-02-20T14:30:00.000Z",
    end_date: "2026-02-20T18:30:00.000Z",
    location_name: "Ledger",
    location_address: "Bentonville, AR",
    is_online: false,
    categories: ["tech", "education"],
    source_url: "https://www.eventbrite.com/d/ar--bentonville/tech/",
    source_platform: "eventbrite",
    organizer_name: "Ledger Bentonville",
    organizer_company: "Ledger",
    status: "approved",
  },
  {
    title: "Black Owned Northwest Arkansas Business Expo",
    description: "The largest showcase of Black-owned businesses in NWA, celebrating Black History Month. Over 60 vendors offering vintage clothing, handcrafted candles, baked goods, samosas, and more. All ages and backgrounds welcome. $5 per person, children under 12 free.",
    start_date: "2026-02-21T17:00:00.000Z",
    end_date: "2026-02-21T22:00:00.000Z",
    location_name: "Fayetteville Town Center",
    location_address: "15 West Mountain Street, Fayetteville, AR 72701",
    is_online: false,
    categories: ["community"],
    source_url: "https://www.eventbrite.com/e/black-owned-northwest-arkansas-business-expo-attendee-registration-tickets-1970601202243",
    source_platform: "eventbrite",
    organizer_name: "JazzyJaeNWA",
    organizer_company: "Black Owned NWA (BONWA)",
    status: "approved",
  },
  {
    title: "Tech Tools Every Entrepreneur Should Know",
    description: "Live demo session on smarter systems for modern founders. Covers tech tools and systems that entrepreneurs should be leveraging.",
    start_date: "2026-02-25T00:00:00.000Z",
    end_date: "2026-02-25T01:30:00.000Z",
    location_name: "The Pryor Center",
    location_address: "Fayetteville, AR",
    is_online: false,
    categories: ["tech", "startup"],
    source_url: "https://www.eventbrite.com/d/ar--bentonville/tech/",
    source_platform: "eventbrite",
    organizer_name: "The Pryor Center",
    status: "approved",
  },
  {
    title: "Workday Arkansas Regional User Group NWA",
    description: "Regional user group meeting for Workday platform users to share tips, tricks, and best practices.",
    start_date: "2026-02-25T20:00:00.000Z",
    end_date: "2026-02-25T23:00:00.000Z",
    location_name: "NorthWest Arkansas Community College",
    location_address: "1 College Drive, Bentonville, AR",
    is_online: false,
    categories: ["tech", "networking"],
    source_url: "https://www.eventbrite.com/d/ar--bentonville/networking/",
    source_platform: "eventbrite",
    organizer_name: "Workday Arkansas Regional User Group",
    status: "approved",
  },
  {
    title: "Send It South: Bike & Music Festival 2026",
    description: "Two-day festival celebrating cycling, live music, and culinary experiences. Winter trail rides across NWA mountains, lakes, and valleys. Inaugural winter bike Olympics on the Momentary campus. Music lineup includes Evan Honer, Winyah, JD Clayton, Adam Faucett, The 502s, Uncle Lucius, RIO KOSTA.",
    start_date: "2026-02-27T17:00:00.000Z",
    end_date: "2026-02-28T23:00:00.000Z",
    location_name: "The Momentary",
    location_address: "507 SE E Street, Bentonville, AR 72712",
    is_online: false,
    categories: ["community"],
    source_url: "https://themomentary.org/calendar/send-it-south/",
    source_platform: "manual",
    organizer_name: "The Momentary",
    organizer_company: "Crystal Bridges",
    status: "approved",
  },
  {
    title: "Black Dynamite Networking",
    description: "Networking event for Black professionals and community members.",
    start_date: "2026-03-04T00:00:00.000Z",
    end_date: "2026-03-04T02:00:00.000Z",
    location_name: "StretchMed",
    location_address: "Bentonville, AR",
    is_online: false,
    categories: ["networking", "community"],
    source_url: "https://www.eventbrite.com/d/ar--bentonville/business-networking/",
    source_platform: "eventbrite",
    organizer_name: "Black Dynamite Networking",
    status: "approved",
  },
  {
    title: "Walmart Campus Grand Opening Celebration",
    description: "Grand opening celebration event related to the new Walmart campus retail/business area.",
    start_date: "2026-03-05T23:30:00.000Z",
    end_date: "2026-03-06T01:30:00.000Z",
    location_name: "Walmart Campus",
    location_address: "1702 SE 8th St, Suite 10, Bentonville, AR",
    is_online: false,
    categories: ["community", "networking"],
    source_url: "https://www.eventbrite.com/d/ar--fayetteville/startup/",
    source_platform: "eventbrite",
    organizer_name: "Walmart",
    organizer_company: "Walmart",
    status: "approved",
  },
  {
    title: "First Friday Free Coworking @ Fayetteville",
    description: "Complimentary coworking day open to anyone interested in trying the space. Great for freelancers, remote workers, and entrepreneurs to work alongside others.",
    start_date: "2026-03-06T14:00:00.000Z",
    end_date: "2026-03-06T23:00:00.000Z",
    location_name: "The Root Coworking",
    location_address: "Bassett Place, Fayetteville, AR",
    is_online: false,
    categories: ["community", "networking"],
    source_url: "https://www.eventbrite.com/e/first-friday-free-coworking-fayetteville-tickets-1268938030809",
    source_platform: "eventbrite",
    organizer_name: "The Root Coworking",
    organizer_company: "The Root",
    status: "approved",
  },
  {
    title: "The Scout Guide NWA 3rd Annual Women's Day Brunch",
    description: "Annual Women's Day brunch event — community and networking for women in NWA.",
    start_date: "2026-03-06T15:00:00.000Z",
    end_date: "2026-03-06T17:00:00.000Z",
    location_name: "The Apollo on Emma",
    location_address: "Springdale, AR",
    is_online: false,
    categories: ["networking", "community"],
    source_url: "https://www.eventbrite.com/d/ar--springdale/northwest-arkansas/",
    source_platform: "eventbrite",
    organizer_name: "The Scout Guide NWA",
    status: "approved",
  },
  {
    title: "NWA Home Show",
    description: "The largest and longest-running home show in the region. The premier event for home enthusiasts in NWA, connecting homeowners with industry leaders in home design, technology, and services. Free parking. All ages. Free admission with registration.",
    start_date: "2026-03-13T16:00:00.000Z",
    end_date: "2026-03-15T22:00:00.000Z",
    location_name: "Rogers Convention Center",
    location_address: "3303 South Pinnacle Hills Parkway, Rogers, AR 72758",
    is_online: false,
    categories: ["community"],
    source_url: "https://www.eventbrite.com/e/nwa-home-show-tickets-1743682704909",
    source_platform: "eventbrite",
    organizer_name: "NWA Home Builders Association",
    status: "approved",
  },
  {
    title: "Information Systems Saturday Preview Day",
    description: "University of Arkansas information session about Information Systems programs for prospective students.",
    start_date: "2026-03-14T17:00:00.000Z",
    end_date: "2026-03-14T19:00:00.000Z",
    location_name: "Reynolds Center for Enterprise Development",
    location_address: "Fayetteville, AR",
    is_online: false,
    categories: ["education", "tech"],
    source_url: "https://www.eventbrite.com/d/ar--bentonville/tech/",
    source_platform: "eventbrite",
    organizer_name: "Walton College",
    organizer_company: "University of Arkansas",
    status: "approved",
  },
  {
    title: "Walton Executive MBA Saturday Preview Day",
    description: "Graduate program information session for the Walton Executive MBA program at the University of Arkansas. Includes complimentary lunch.",
    start_date: "2026-03-14T17:00:00.000Z",
    end_date: "2026-03-14T19:00:00.000Z",
    location_name: "Willard J. Walker Hall",
    location_address: "Fayetteville, AR",
    is_online: false,
    categories: ["education", "career"],
    source_url: "https://www.eventbrite.com/d/ar--fayetteville/networking/",
    source_platform: "eventbrite",
    organizer_name: "Walton Graduate School of Business",
    organizer_company: "University of Arkansas",
    status: "approved",
  },
  {
    title: "Technobotics Foundation Fundraiser",
    description: "Fundraiser for the Technobotics Foundation, a STEM/robotics education nonprofit. Includes robot reveals, silent auction, and dinner.",
    start_date: "2026-03-18T00:00:00.000Z",
    end_date: "2026-03-18T03:00:00.000Z",
    location_name: "Thaden School: Great Hall",
    location_address: "Bentonville, AR",
    is_online: false,
    categories: ["tech", "education", "community"],
    source_url: "https://www.visitbentonville.com/event/technobotics-foundation-fundraiser/9650/",
    source_platform: "manual",
    organizer_name: "Technobotics Foundation",
    status: "approved",
  },
  {
    title: "Masters of Science in Economic Analytics — Lunch and Learn",
    description: "Informational lunch and learn about the Masters of Science in Economic Analytics program at the University of Arkansas. Available in-person and virtually.",
    start_date: "2026-03-18T18:00:00.000Z",
    end_date: "2026-03-18T19:00:00.000Z",
    location_name: "Willard J. Walker Hall",
    location_address: "Fayetteville, AR",
    is_online: false,
    categories: ["education", "career"],
    source_url: "https://www.eventbrite.com/d/ar--fayetteville/networking/",
    source_platform: "eventbrite",
    organizer_name: "Walton Graduate School of Business",
    organizer_company: "University of Arkansas",
    status: "approved",
  },
  {
    title: "HackNWA 2026: Holiday in Scambodia",
    description: "Annual cybersecurity conference with two talking tracks and tech village. Features speaker lineup, activities, panelists, exhibits, badge/hardware hacking, solder village, and challenges.",
    start_date: "2026-04-17T14:00:00.000Z",
    end_date: "2026-04-17T23:00:00.000Z",
    location_name: "Shewmaker Center for Global Business Development",
    location_address: "Bentonville, AR",
    is_online: false,
    categories: ["tech", "community"],
    source_url: "https://hacknwa.org/",
    source_platform: "manual",
    organizer_name: "HackNWA",
    status: "approved",
  },
];

async function seed() {
  console.log("Clearing fake seed data...");
  await supabase.from("events").delete().neq("id", "00000000-0000-0000-0000-000000000000");

  console.log(`Inserting ${events.length} real NWA events...`);
  const { data, error } = await supabase.from("events").insert(events).select();

  if (error) {
    console.error("Failed to seed:", error);
    return;
  }

  console.log(`Seeded ${data.length} real events successfully!`);
}

seed().catch(console.error);
